version: '3.9'

networks:
  local:
    external: true

services:
  server:
    container_name: server
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    networks:
      - local
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - NODE_ENV=development
