apiVersion: v1
kind: Secret
metadata:
  name: gh-registry-creds
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.gh_credentials | b64enc }}
