apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: {{ .Chart.Name }}
  selector: {{- include "chart.selectorLabels" . | nindent 4 }}
